### ISSUE TITLE
No typ in header

### ISSUE THREAD

**Issue by grim-bees** [pascaldekloe/jwt#7]
Hi,

I just wandering can we put typ in the header?

Thanks

**Comment by pascaldekloe** [comment]
Of course. There needs to be a reason though.
Adding a field makes tokens larger, and I remember reading somewhere the use was depreciated.

Why would you like the typ inclusion?

**Comment by grim-bees** [comment]
The spec-wise mention that header type is optional, can we make it optionally available as well?

**Comment by pascaldekloe** [comment]
Yes we can. Just give me a reason to do so.

**Comment by lusk** [comment]
IMHO it would make debugging easier. If the validating side uses "typ": "JWT" in their headers and for some reason rejects your token as invalid, first order of business is to try to have the header and payload match EXACTLY to theirs in order to be able to rule out other possibilities before you can be sure that you are using a wrong secret for signing in the first place.

**Comment by pascaldekloe** [comment]
Good point. An unusual one, but valid none the less. I think this "typ" header is so lame, that it does not deserve a switch of it's own. Maybe serve with a catch-all as Claims.ExtraHeaders map[string]interface{}?
